baseURL = "https://scenic-shop.com/test2/"
languageCode = "en-us"
title = "Scenic-Shop"
theme = "minimal"
#disqusShortname = "username" # delete this to disable disqus comments
#googleAnalytics = ""

[params]
    author = "Matthew D. Jordan"
    description = "Technical Theatre Musings and Articles"
    githubUsername = "jordanrobot"
    accent = "darkcyan"
    showBorder = true
    backgroundColor = "white"
    font = "Roboto" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["lisp", "bash", "dos", "csharp", "vbnet"]

[[menu.main]]
    url = "/"
    name = "home"
    weight = 1

[[menu.main]]
    url = "/projects/"
    name = "projects"
    weight = 3

[[menu.main]]
    url = "/posts/"
    name = "posts"
    weight = 2

[[menu.main]]
    url = "https://www.scenic-shop.com/Calculators"
    name = "calculators"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

#[[menu.icon]]
#    url = "mailto:me@example.com"
#    name = "envelope-o"
#    weight = 1

[[menu.icon]]
    url = "https://github.com/jordanrobot/"
    name = "github"
    weight = 2

#[[menu.icon]]
#    url = "https://twitter.com/username/"
#    name = "twitter"
#    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/username/"
    name = "linkedin"
    weight = 4

